version: '3'
services:

  ekucniljubimci-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chelsea321!
      - MSSQL_PID=Developer
    ports:
      - 1416:1433
    expose:
      - 1433
    networks:
      - ekucniljubimcinet

  ekucniljubimci-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ekucniljubimci-sql,1433;Database=eKucniLjubimci;User=sa;Password=Chelsea321!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7152:7152
    networks:
      - ekucniljubimcinet
    links:
      - ekucniljubimci-sql
    depends_on:
      - ekucniljubimci-sql
      
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: ekucniljubimci-rmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ekucniljubimcinet
      
networks:
  ekucniljubimcinet:
    driver: bridge      