version: '3'
services:

  ekucniljubimci-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chelsea321!
      - MSSQL_PID=Developer
    ports:
      - 1417:1433
    expose:
      - 1433
    networks:
      - ekucniljubimcinet     

  ekucniljubimci-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ekucniljubimci-sql,1433;Database=IB180121;User=sa;Password=Chelsea321!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=testUsername
      - RabbitMQ_Password=testPassword
      - RabbitMQ_Port=5672
      - RabbitMQ_MailAdressFrom=murl87@ethereal.email
      - RabbitMQ_MailAdressTo=murl87@ethereal.email
      - RabbitMQ_MailAdressPassword=jCf9JwZUVATxEkvv1F
      - RabbitMQ_MailSMTP=smtp.ethereal.email  
      - RabbitMQ_MailPort=587         
    ports:
      - 7152:7152
    networks:
      - ekucniljubimcinet
    links:
      - ekucniljubimci-sql
    depends_on:
      - ekucniljubimci-sql
      - rabbitmq    

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped  
    environment:
      - RABBITMQ_DEFAULT_USER=testUsername
      - RABBITMQ_DEFAULT_PASS=testPassword 
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ekucniljubimcinet      

  ekucniljubimci-console:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.RabbitMQ.Receiver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=testUsername
      - RabbitMQ_Password=testPassword
      - RabbitMQ_Port=5672
    ports:
      - 7252:7252
    networks:
      - ekucniljubimcinet
    depends_on:
      - ekucniljubimci-api
      - ekucniljubimci-sql
      - rabbitmq
      
networks:
  ekucniljubimcinet:
    driver: bridge      