version: '3'
services:

  ekucniljubimci-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chelsea321!
      - MSSQL_PID=Developer
    ports:
      - 1417:1433
    expose:
      - 1433
    networks:
      - ekucniljubimcinet     

  ekucniljubimci-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ekucniljubimci-sql,1433;Database=IB180121;User=sa;Password=Chelsea321!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
      - RabbitMQ_Port=5672
      - RabbitMQ_MailAdressFrom=rocky58@ethereal.email
      - RabbitMQ_MailAdressTo=rocky58@ethereal.email
      - RabbitMQ_MailAdressPassword=4VufRUy2Ayw98CsKR3
      - RabbitMQ_MailSMTP=smtp.ethereal.email      
    ports:
      - 7152:7152
    networks:
      - ekucniljubimcinet
    links:
      - ekucniljubimci-sql
    depends_on:
      - ekucniljubimci-sql
      - rabbitmq    

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped  
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest 
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ekucniljubimcinet       
      
networks:
  ekucniljubimcinet:
    driver: bridge      